# Site wide configuration

title: Comtravo Tech
title_img: <img src=/images/comtravo-logo.png />
description: ""
logo: ct-logo-120x120.png # 120x120 px default image used for Twitter summary card
teaser: ct_teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: https://tech.comtravo.com
feed:
  path: atom.xml
future: false
timezone: Europe/Berlin

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category-archive

# Site owner
owner:
  name: Comtravo Tech
  email: tech@comtravo.com
  twitter: comtravo_travel
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: ct-logo-120x120.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
